import { Router } from 'express';
import { z } from 'zod';
import sanitizeHtml from 'sanitize-html';
import { query } from '../database/pool.js';
import { requireAuth } from '../middleware/auth.js';
import { validate } from '../middleware/validate.js';
const clean=v=>typeof v==='string'?sanitizeHtml(v,{allowedTags:[],allowedAttributes:{}}).trim():v;
export const memories=Router().use(requireAuth);
const memorySchema=z.object({category:z.string().max(50).default('general'),key:z.string().min(1).max(120).transform(clean),value:z.any(),importance:z.number().int().min(1).max(5).default(3)});
memories.post('/',validate(memorySchema),async(req,res)=>{const b=req.body;const r=await query(`insert into memories(user_id,category,key,value,importance) values($1,$2,$3,$4,$5) returning *`,[req.user.id,b.category,b.key,b.value,b.importance]);res.status(201).json({success:true,memory:r.rows[0]});});
memories.get('/',async(req,res)=>{const r=await query('select * from memories where user_id=$1 order by importance desc,updated_at desc',[req.user.id]);res.json({success:true,memories:r.rows});});
memories.put('/:id',validate(memorySchema.partial()),async(req,res)=>{const current=await query('select * from memories where id=$1 and user_id=$2',[req.params.id,req.user.id]);if(!current.rowCount)return res.status(404).json({success:false,error:'Memory not found'});const b={...current.rows[0],...req.body};const r=await query(`update memories set category=$1,key=$2,value=$3,importance=$4,updated_at=now() where id=$5 and user_id=$6 returning *`,[b.category,b.key,b.value,b.importance,req.params.id,req.user.id]);res.json({success:true,memory:r.rows[0]});});
memories.delete('/:id',async(req,res)=>{const r=await query('delete from memories where id=$1 and user_id=$2 returning id',[req.params.id,req.user.id]);res.status(r.rowCount?200:404).json(r.rowCount?{success:true}:{success:false,error:'Memory not found'});});

function resourceRouter(table,schema,label){const r=Router().use(requireAuth);r.post('/',validate(schema),async(req,res)=>{const b=req.body;if(table==='notes'){const q=await query(`insert into notes(user_id,title,content,tags,priority) values($1,$2,$3,$4,$5) returning *`,[req.user.id,clean(b.title),clean(b.content),b.tags,b.priority]);return res.status(201).json({success:true,[label]:q.rows[0]});}const q=await query(`insert into tasks(user_id,title,description,due_at,priority,status,reminder_at) values($1,$2,$3,$4,$5,$6,$7) returning *`,[req.user.id,clean(b.title),clean(b.description||''),b.dueAt||null,b.priority,b.status,b.reminderAt||null]);res.status(201).json({success:true,[label]:q.rows[0]});});r.get('/',async(req,res)=>{const q=await query(`select * from ${table} where user_id=$1 order by updated_at desc`,[req.user.id]);res.json({success:true,[table]:q.rows});});r.put('/:id',validate(schema.partial()),async(req,res)=>{const old=await query(`select * from ${table} where id=$1 and user_id=$2`,[req.params.id,req.user.id]);if(!old.rowCount)return res.status(404).json({success:false,error:`${label} not found`});const b={...old.rows[0],...req.body};let q;if(table==='notes')q=await query(`update notes set title=$1,content=$2,tags=$3,priority=$4,updated_at=now() where id=$5 and user_id=$6 returning *`,[clean(b.title),clean(b.content),b.tags,b.priority,req.params.id,req.user.id]);else q=await query(`update tasks set title=$1,description=$2,due_at=$3,priority=$4,status=$5,reminder_at=$6,updated_at=now() where id=$7 and user_id=$8 returning *`,[clean(b.title),clean(b.description||''),b.dueAt||b.due_at||null,b.priority,b.status,b.reminderAt||b.reminder_at||null,req.params.id,req.user.id]);res.json({success:true,[label]:q.rows[0]});});r.delete('/:id',async(req,res)=>{const q=await query(`delete from ${table} where id=$1 and user_id=$2 returning id`,[req.params.id,req.user.id]);res.status(q.rowCount?200:404).json(q.rowCount?{success:true}:{success:false,error:`${label} not found`});});return r;}
export const notes=resourceRouter('notes',z.object({title:z.string().min(1).max(160),content:z.string().max(20000).default(''),tags:z.array(z.string().max(40)).max(20).default([]),priority:z.enum(['low','normal','high','critical']).default('normal')}),'note');
export const tasks=resourceRouter('tasks',z.object({title:z.string().min(1).max(160),description:z.string().max(10000).default(''),dueAt:z.string().datetime().nullable().optional(),priority:z.enum(['low','normal','high','critical']).default('normal'),status:z.enum(['pending','in_progress','completed','cancelled']).default('pending'),reminderAt:z.string().datetime().nullable().optional()}),'task');
